Task 3: Update / Edit Todo
ashrafkabir2001/todo-app pull request #3
Opened 2024-02-28 08:50 UTC by aks-wtag

Objectives:
- [x] Beside each todo, there is another new button named Edit.
- [x] Clicking the Edit todo button will the turn the current Todo text content into an input box.
- [x] When in Edit Mode, The text of Add button is changed from Edit to Update.
- [x] If a user clicked the edit button, but don’t want any changes, then there should be a button named cancel to go back to the previous state.

[T3.webm](https://github.com/aks-wtag/todo-app/assets/152831915/e1877378-4f2a-49ad-833b-27e32aff88ec)

2024-02-29 10:13 UTC, njm-wtag requested changes

2024-02-29 10:13 UTC, njm-wtag commented on js/script.js
> +    taskList.map((t) => {
It's not recommended to use meaningless variable name rather we can use `todo` or `singleTask` insted of `t`

2024-02-29 10:39 UTC, njm-wtag commented on js/script.js
> +        if(t.id==task.id){
```suggestion
        if(t.id===task.id){
```

2024-02-29 10:41 UTC, njm-wtag commented on js/script.js
> +    task.title = $inputField.value;
What happen if input value is empty? We can check error

2024-02-29 10:43 UTC, njm-wtag commented on js/script.js
> +    taskList.map((t) => {
Why are we using `map` here? As its return a new array. We can use `find` instead.

2024-03-03 11:42 UTC, njm-wtag approved these changes

2024-03-04 04:40 UTC, hhu-wtag approved these changes

2024-03-04 04:40 UTC, hhu-wtag commented on js/script.js
> +        return;
```suggestion
        showErrorMessage("Task Title must be provided for edit");
        
        return;
```

2024-03-04 04:40 UTC, hhu-wtag commented on js/utility.js
add eol

2024-03-18 09:52 UTC, closed without merging