Task 6: Overall UI design
ashrafkabir2001/todo-app pull request #6
Opened 2024-03-05 08:02 UTC by aks-wtag

Objective:
Implement the UI of the app including the previous features.

(Note: The filter and the load more buttons are not added any functionality yet)
[T6.webm](https://github.com/aks-wtag/todo-app/assets/152831915/b4f226e7-3e91-40b3-adf7-87a2d9476bc9)

2024-03-06 10:16 UTC, mza-wtag commented on css/mystrap.css
Please provide a meaningful name for the file. 

2024-03-06 10:16 UTC, mza-wtag commented on css/mystrap.css
> +    font-weight: 500;
Take it within a variable, please.

2024-03-06 10:16 UTC, mza-wtag commented on js/utility.js
>  };
Implement this functionality for adding tasks as well. 

2024-03-06 12:10 UTC, mza-wtag reviewed
Please update the UI of the cancel button and fix the issues. When you are in edit mode and click the complete button, it should be completed with the updated values, redirect it to the initial completed state, and handle the edit button properly, as after the task is done, the edit button is still remaining. 

2024-03-07 04:01 UTC, ich-wtag reviewed
![Screenshot from 2024-03-07 09-49-45](https://github.com/aks-wtag/todo-app/assets/153156568/d4f055d2-55cc-493d-b2a0-18d4fa2bde0a)
When you click on this blank box, the blank input field should be opened.


[Screencast from 03-07-2024 09:50:38 AM.webm](https://github.com/aks-wtag/todo-app/assets/153156568/caf72088-2894-471c-a2d2-a90639623c28)
Like when you add any task filter button is not reflecting the changes. I noticed you have different Feature branch for that, if it is please move this buttons **UI** to that branch. It's better to have related functionalities to be in single branch.

Finally you have added a render function. Can you please use this for function for add task too. Cause each function should be tried to keep pure and reusable. So as render function is a reusable function we should reuse it and modify it to use maximum places as much as we can. Thanks bhai.

2024-03-07 04:48 UTC, aks-wtag commented
@ich-wtag bhai i have shown the text area when the image is clicked and removed the filter buttons. Bhai the render function is not needed for add, delete or edit task here but while implementing the pagination in the upcoming branch i had to use the render function for add and delete so i have changed it there. Thanks.

2024-03-07 05:01 UTC, njm-wtag requested changes
![Screenshot from 2024-03-07 10-55-40](https://github.com/aks-wtag/todo-app/assets/148762372/a9772bd2-f864-4d3c-bde1-645f0d6169bd)

Clicking on search icon is not opening search input box

2024-03-07 05:05 UTC, njm-wtag requested changes
[Screencast from 7-3-24 11:03:29 পূর্বাহ্ণ +06.webm](https://github.com/aks-wtag/todo-app/assets/148762372/db88c7de-bd74-4927-8647-6cd75a4f198f)

Please fix it

2024-03-07 05:36 UTC, ich-wtag approved these changes

2024-03-07 08:34 UTC, njm-wtag approved these changes

2024-03-07 09:28 UTC, rka-wtag approved these changes

2024-03-07 09:28 UTC, mza-wtag approved these changes

2024-03-12 07:13 UTC, hhu-wtag approved these changes

2024-03-18 09:52 UTC, closed without merging